/* eslint-disable @typescript-eslint/no-var-requires */
// This file is generated by `npx ts-jest config:init`, see https://github.com/kulshekhar/ts-jest/blob/102c829/README.md#getting-started
const fs = require('fs')
const path = require('path')
const stripJsonComments = require('strip-json-comments')
const { pathsToModuleNameMapper } = require('ts-jest/utils')

const tsconfig = JSON.parse(
  stripJsonComments(
    fs.readFileSync(path.join(__dirname, 'tsconfig.json'), 'utf-8'),
  ),
)

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  // Doc: https://github.com/kulshekhar/ts-jest/blob/05916b9/docs/user/config/index.md#paths-mapping
  moduleNameMapper: pathsToModuleNameMapper(tsconfig.compilerOptions.paths, {
    prefix: '<rootDir>/',
  }),
}
